# @name createTodo
POST http://localhost:3000/todos
Content-Type: application/json

{
  "title": "Serverless challenge",
  "description": "Create a serverless application using Serverless Framework",
  "dueDate": "2024-06-05"
}

###
# @name listTodos
GET http://localhost:3000/todos

###
# @name getTodo
GET http://localhost:3000/todos/{{createTodo.response.body.todo.id}}

###
# @name completeTodo
PATCH http://localhost:3000/todos/{{createTodo.response.body.todo.id}}/complete

###
# @name deleteTodo
DELETE http://localhost:3000/todos/{{createTodo.response.body.todo.id}}